### ISSUE TITLE
Check and Disable  DOTNET_CLI_TELEMETRY_OPTOUT if really enabled

### ISSUE THREAD

**Issue by hensou** [hensou/asdf-dotnet#16]
**Is your feature request related to a problem? Please describe.**

It seems that [Microsoft enables telemetry by default](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script#description) on the installation of the SDK via the installer script.

**Describe the solution you'd like**

Telemetry should be disabled by default

**Additional context**

[How to disable telemetry](https://learn.microsoft.com/en-us/dotnet/core/tools/telemetry#how-to-opt-out)

**Comment by oleksbabieiev** [comment]
Correct me if I'm wrong, but as far as I know, different shells have different ways of setting global variables, but the vast majority of them support adding `export NAME=VALUE` to the configuration file. However, it's not so simple, because the configuration file is also different for different shells and can be located in different places. I doubt that disabling telemetry can be automated with a universal shell script. I would just add a warning to `README.md`. This seems to me to be the simplest and most straightforward solution.

**Comment by hensou** [comment]
Thanks for you contribution @oleksbabieiev , I'll accept your PR as for now, it is the simplest solution to this.

However, I'm failling to imagine a scenario where adding the variable to the environment would not be enough. I mean, we already do that for the `DOTNET_*` variables on the `set-dotnet-env.{fish,zsh,bash}` files, wouldn't that be the same case here?

**Comment by oleksbabieiev** [comment]
Okay, my "interesting" idea didn't live up to expectations 😂. Perhaps it would have been better to do what you said, just making small adjustments to the existing scripts `set-dotnet-env.*`, and not reinvent the wheel.
